'use client';

import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import { useRouter } from 'next/navigation';
import { Plus, Folder, ArrowRight, X, Clock, Trash2, Sparkles } from 'lucide-react';
import Navbar from '../layout/Navbar';
import { kanbanService, Project } from '../../services/kanbanService';
import { useAuth } from '../../hooks/useAuth';
import { EmptyState } from '../ui';
import type { GenerateProjectResponse } from '../board/GenerateProjectModal';
import { Card } from '../../types/kanban';

// AI generátor projektu -- lazy load (těžký, otevírá se zřídka)
const GenerateProjectModal = dynamic(() => import('../board/GenerateProjectModal'), { ssr: false });
import { aiHistoryService } from '../../services/ai/aiHistoryService';

export default function ProjectDashboard() {
  const router = useRouter();
  const { user } = useAuth();
  const [projects, setProjects] = useState<Project[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false);
  const [newProjectName, setNewProjectName] = useState('');
  const [projectToDelete, setProjectToDelete] = useState<Project | null>(null);
  const [error, setError] = useState('');

  const handleGenerateProjectAccept = async (data: GenerateProjectResponse) => {
    if (!user) return;
    try {
      // 1. Capture snapshot before project creation synchronously
      const snapshot = aiHistoryService.captureSnapshot('', null, projects);

      // 2. Vytvořit projekt
      const createdProject = await kanbanService.createProject(data.name, user.id);

      // Associate the created project ID with the snapshot for future revert (deletion)
      snapshot.projectId = createdProject.id;
      snapshot.projectName = createdProject.name;

      // 3. Vložit sloupce doporučené od AI
      const savedColumns = await kanbanService.saveProjectColumns(
        createdProject.id,
        data.recommendedColumns || ['Todo', 'In Progress', 'Done']
      );

      // 4. Vytvořit úkoly z backlogu
      let totalTasksGenerated = 0;
      for (const task of data.tasks) {
        let col = savedColumns.find(
          (c) => c.name.trim().toLowerCase() === task.recommendedColumn.trim().toLowerCase()
        );
        if (!col && savedColumns.length > 0) {
          col = savedColumns[0];
        }

        if (col) {
          const cardId = `card-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
          
          let details = task.description || '';
          if (task.estimate) {
            details += `\n\n**Odhadovaný čas:** ${task.estimate}`;
          }
          if (task.acceptanceCriteria && task.acceptanceCriteria.length > 0) {
            details += `\n\n### Kritéria akceptace:\n` + task.acceptanceCriteria.map((c: string) => `- ${c}`).join('\n');
          }

          const newCard: Card = {
            id: cardId,
            title: task.title,
            details,
            priority: task.priority || undefined,
            archived: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            checklist: (task.checklist || []).map((text: string) => ({
              id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
              text,
              completed: false,
            })),
            comments: [],
            activities: [
              {
                id: `act-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
                text: 'Project generated by AI',
                createdAt: new Date().toISOString(),
              },
              {
                id: `act-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
                text: 'Backlog imported by AI',
                createdAt: new Date().toISOString(),
              }
            ]
          };

          await kanbanService.createCard(col.id, newCard, col.cards.length, createdProject.id);
          totalTasksGenerated++;

          if (newCard.activities) {
            await kanbanService.addActivity(cardId, newCard.activities[0]);
            await kanbanService.addActivity(cardId, newCard.activities[1]);
          }
        }
      }

      // 5. Uložit záznam do historie
      aiHistoryService.saveHistoryRecord(
        'AI Generate Project',
        createdProject.name,
        `Vygenerován celý projekt "${createdProject.name}" s ${totalTasksGenerated} úkoly`,
        totalTasksGenerated,
        snapshot
      );

      router.push(`/projects/${createdProject.id}`);
    } catch (err) {
      console.error('Failed to generate project flow:', err);
      throw new Error('Nepodařilo se dokončit vytváření a import projektu.');
    }
  };

  useEffect(() => {
    async function loadProjects() {
      if (!user) return;
      setIsLoading(true);
      try {
        const data = await kanbanService.fetchProjects(user.id);
        setProjects(data);
      } catch (err) {
        console.error('Failed to load projects:', err);
      } finally {
        setIsLoading(false);
      }
    }
    loadProjects();
  }, [user]);

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault();
    const name = newProjectName.trim();
    if (!name) {
      setError('Název projektu je povinný');
      return;
    }

    try {
      const created = await kanbanService.createProject(name, user?.id);
      setProjects((prev) => [created, ...prev]);
      setNewProjectName('');
      setIsModalOpen(false);
      setError('');
      // Automaticky přesměrovat na nově vytvořený projekt
      router.push(`/projects/${created.id}`);
    } catch (err) {
      console.error('Failed to create project:', err);
      setError('Nepodařilo se vytvořit projekt.');
    }
  };

  const handleDeleteClick = (e: React.MouseEvent, project: Project) => {
    e.stopPropagation();
    setProjectToDelete(project);
  };

  const handleConfirmDelete = async () => {
    if (!projectToDelete) return;
    try {
      await kanbanService.deleteProject(projectToDelete.id);
      setProjects((prev) => prev.filter((p) => p.id !== projectToDelete.id));
      setProjectToDelete(null);
    } catch (err) {
      console.error('Failed to delete project:', err);
      alert('Nepodařilo se odstranit projekt.');
    }
  };

  return (
    <div className="app-container" style={{ overflowY: 'auto' }}>
      <Navbar />

      {/* Hero sekce dashboardu */}
      <section className="app-hero">
        <div className="hero-content">
          <div className="hero-left">
            <span className="hero-team-label">VÍTEJTE V PORTÁLU</span>
            <h1 className="hero-title">Vaše projekty.</h1>
            <p className="hero-desc">Čistý prostor pro koordinaci a plánování vašich týmů.</p>
          </div>
          <div className="hero-right">
            {/* CTA buttons removed to focus on distinct premium cards below */}
          </div>
        </div>
      </section>

      {/* Mřížka projektů */}
      <main style={{ padding: '0 3rem 3rem 3rem', maxWidth: '1600px', margin: '0 auto', width: '100%' }}>
        {/* Premium CTA Cards for Project Creation */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))', gap: '1.5rem', marginBottom: '2.5rem' }}>
          {/* Card 1: Classic Creation */}
          <div
            onClick={() => setIsModalOpen(true)}
            style={{
              padding: '2.25rem 2rem',
              cursor: 'pointer',
              backgroundColor: 'var(--surface)',
              border: '2px dashed var(--border-color)',
              borderRadius: 'var(--radius-card)',
              display: 'flex',
              alignItems: 'center',
              gap: '1.5rem',
              transition: 'all 0.2s ease-in-out',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = 'var(--blue-primary)';
              e.currentTarget.style.transform = 'translateY(-2px)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = 'var(--border-color)';
              e.currentTarget.style.transform = 'translateY(0)';
            }}
            data-testid="classic-new-project-cta"
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '48px', height: '48px', borderRadius: 'var(--radius-card)', backgroundColor: 'var(--accent-soft)', color: 'var(--accent)', flexShrink: 0 }}>
              <Plus size={24} />
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              <h3 style={{ fontSize: '1rem', fontWeight: 800, color: 'var(--dark-navy)', margin: 0 }}>➕ New Project</h3>
              <p style={{ fontSize: '0.75rem', color: 'var(--gray-text)', margin: 0 }}>Vytvořit prázdný projekt a začít od čistého boardu.</p>
            </div>
          </div>

          {/* Card 2: AI Generation */}
          <div
            onClick={() => setIsGenerateModalOpen(true)}
            style={{
              padding: '2.25rem 2rem',
              cursor: 'pointer',
              background: 'var(--accent-soft)',
              border: '1px solid var(--accent-ring)',
              borderRadius: 'var(--radius-card)',
              display: 'flex',
              alignItems: 'center',
              gap: '1.5rem',
              transition: 'all 0.2s ease-in-out',
              position: 'relative',
              overflow: 'hidden'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = 'var(--accent)';
              e.currentTarget.style.transform = 'translateY(-2px)';
              e.currentTarget.style.boxShadow = 'var(--shadow-md)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = 'var(--accent-ring)';
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = 'none';
            }}
            data-testid="ai-generate-project-cta"
          >
            <div style={{ position: 'absolute', top: '0.6rem', right: '0.6rem', fontSize: '0.55rem', fontWeight: 800, background: 'var(--purple-secondary)', color: '#ffffff', padding: '0.15rem 0.45rem', borderRadius: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              AI Engine
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: '48px', height: '48px', borderRadius: 'var(--radius-card)', backgroundColor: 'var(--surface)', color: 'var(--accent)', flexShrink: 0 }}>
              <Sparkles size={22} />
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              <h3 style={{ fontSize: '1rem', fontWeight: 800, color: 'var(--purple-secondary)', margin: 0 }}>✨ Generate Project</h3>
              <p style={{ fontSize: '0.75rem', color: 'var(--gray-text)', margin: 0 }}>AI navrhne na míru celou architekturu sloupců i backlog.</p>
            </div>
          </div>
        </div>

        {isLoading ? (
          <div style={{ display: 'flex', justifyContent: 'center', padding: '4rem 0', color: 'var(--gray-text)', fontSize: '0.9rem', fontWeight: 600 }}>
            Načítání projektů...
          </div>
        ) : projects.length === 0 ? (
          <EmptyState
            icon={<Folder size={28} />}
            title="Žádné projekty"
            description="Zatím nemáte žádné projekty. Využijte možnosti výše pro vytvoření nového projektu."
          />
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(320px, 100%), 1fr))', gap: '1.5rem' }}>
            {projects.map((project) => (
              <div
                key={project.id}
                onClick={() => router.push(`/projects/${project.id}`)}
                className="project-card"
                data-testid={`project-card-${project.id}`}
              >
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--blue-primary)' }}>
                      <Folder size={18} />
                      <span style={{ fontSize: '0.65rem', fontWeight: 700, letterSpacing: '0.05em', textTransform: 'uppercase' }}>PROJEKT</span>
                    </div>
                    {project.id !== 'project-default' && (
                      <button
                        type="button"
                        className="project-delete-btn"
                        onClick={(e) => handleDeleteClick(e, project)}
                        style={{
                          background: 'none',
                          border: 'none',
                          color: 'var(--gray-text)',
                          cursor: 'pointer',
                          padding: '4px',
                          borderRadius: '4px',
                          transition: 'color 0.2s ease',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                        }}
                        onMouseEnter={(e) => (e.currentTarget.style.color = 'var(--danger)')}
                        onMouseLeave={(e) => (e.currentTarget.style.color = 'var(--gray-text)')}
                        data-testid={`delete-project-btn-${project.id}`}
                        title="Odstranit projekt"
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                  </div>
                  <h3 style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--dark-navy)', letterSpacing: '-0.015em' }}>
                    {project.name}
                  </h3>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: '1rem', borderTop: '1px solid var(--border-color)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: 'var(--gray-text)', fontSize: '0.65rem', fontWeight: 500 }}>
                    <Clock size={12} />
                    <span>{project.created_at ? new Date(project.created_at).toLocaleDateString('cs-CZ') : 'Nedávno'}</span>
                  </div>
                  <div style={{ color: 'var(--purple-secondary)', display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.75rem', fontWeight: 700 }}>
                    <span>Otevřít</span>
                    <ArrowRight size={14} />
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* Modal pro vytvoření projektu */}
      {isModalOpen && (
        <div className="modal-overlay" onClick={() => setIsModalOpen(false)}>
          <div
            className="modal-content"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-modal="true"
          >
            <div className="modal-header">
              <h2 className="modal-title">Nový projekt</h2>
              <button
                type="button"
                className="modal-close-btn"
                onClick={() => setIsModalOpen(false)}
                aria-label="Zavřít okno"
              >
                <X size={20} />
              </button>
            </div>
            <form onSubmit={handleCreateProject}>
              <div className="modal-body">
                <div className="form-group">
                  <label htmlFor="project-name" className="form-label">
                    Název projektu *
                  </label>
                  <input
                    id="project-name"
                    type="text"
                    className="form-input"
                    placeholder="Zadejte název projektu"
                    value={newProjectName}
                    onChange={(e) => {
                      setNewProjectName(e.target.value);
                      if (error) setError('');
                    }}
                    autoFocus
                    data-testid="project-name-input"
                  />
                  {error && (
                    <p style={{ color: 'var(--danger)', fontSize: '0.75rem', marginTop: '0.25rem' }}>
                      {error}
                    </p>
                  )}
                </div>
              </div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-cancel"
                  onClick={() => setIsModalOpen(false)}
                >
                  Zrušit
                </button>
                <button type="submit" className="btn btn-submit" data-testid="project-submit-btn">
                  Vytvořit projekt
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal pro potvrzení smazání projektu */}
      {projectToDelete && (
        <div className="modal-overlay" onClick={() => setProjectToDelete(null)}>
          <div
            className="modal-content"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-modal="true"
            data-testid="delete-project-modal"
          >
            <div className="modal-header">
              <h2 className="modal-title" style={{ color: 'var(--danger)' }}>Odstranit projekt</h2>
              <button
                type="button"
                className="modal-close-btn"
                onClick={() => setProjectToDelete(null)}
                aria-label="Zavřít okno"
              >
                <X size={20} />
              </button>
            </div>
            <div className="modal-body">
              <p style={{ fontSize: '0.85rem', color: 'var(--dark-navy)', fontWeight: 600, marginBottom: '0.75rem' }}>
                Opravdu chcete odstranit projekt: <span style={{ color: 'var(--purple-secondary)', fontWeight: 700 }}>{projectToDelete.name}</span>?
              </p>
              <p style={{ fontSize: '0.75rem', color: 'var(--gray-text)', lineHeight: '1.4' }}>
                Varování: Tato akce je zcela nevratná. Odstraněním projektu dojde k trvalému smazání všech jeho boardů, sloupců, karet a veškerých souvisejících dat.
              </p>
            </div>
            <div className="modal-footer">
              <button
                type="button"
                className="btn btn-cancel"
                onClick={() => setProjectToDelete(null)}
              >
                Zrušit
              </button>
              <button
                type="button"
                className="btn btn-delete"
                onClick={handleConfirmDelete}
                data-testid="delete-project-confirm-btn"
              >
                Odstranit projekt
              </button>
            </div>
          </div>
        </div>
      )}

      {isGenerateModalOpen && (
        <GenerateProjectModal
          isOpen={isGenerateModalOpen}
          onClose={() => setIsGenerateModalOpen(false)}
          onAccept={handleGenerateProjectAccept}
        />
      )}
    </div>
  );
}
